CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100),
    password VARCHAR(255),
    location VARCHAR(255),
    state VARCHAR(100)
);

INSERT INTO users (name, email, password, location, state) VALUES
('Alice Johnson', 'alice.johnson@example.com', 'password123', '123 Main St', 'California'),
('Bob Smith', 'bob.smith@example.com', 'securepassword', '456 Oak Ave', 'Texas'),
('Charlie Brown', 'charlie.brown@example.com', 'charliepass', '789 Pine Blvd', 'New York'),
('Diana Ross', 'diana.ross@example.com', 'rosspassword', '101 Maple Dr', 'Florida'),
('Edward Walker', 'edward.walker@example.com', 'edwardpw', '202 Birch St', 'Nevada'),
('Fiona Green', 'fiona.green@example.com', 'fiona123', '303 Cedar Ln', 'Oregon'),
('George Miller', 'george.miller@example.com', 'georgepassword', '404 Elm Rd', 'Illinois'),
('Hannah Lee', 'hannah.lee@example.com', 'hannah123', '505 Pinecrest Dr', 'Michigan'),
('Isaac Adams', 'isaac.adams@example.com', 'isaacpass', '606 Willow Way', 'Ohio'),
('Jack Wilson', 'jack.wilson@example.com', 'jack1234', '707 Oakwood Ave', 'Texas'),
('Karen Davis', 'karen.davis@example.com', 'karenpw', '808 Maplewood Dr', 'California'),
('Louis White', 'louis.white@example.com', 'louispass', '909 Fir Ct', 'New York'),
('Maggie Taylor', 'maggie.taylor@example.com', 'maggiepass', '1010 Cedar Dr', 'Florida'),
('Nathan Scott', 'nathan.scott@example.com', 'nathan123', '1111 Pinehill Rd', 'Nevada'),
('Olivia Harris', 'olivia.harris@example.com', 'olivia123', '1212 Oak Rd', 'Oregon'),
('Peter Clark', 'peter.clark@example.com', 'peterpw', '1313 Maple Dr', 'Illinois'),
('Quinn Davis', 'quinn.davis@example.com', 'quinnpass', '1414 Elm St', 'Michigan'),
('Rachel Thompson', 'rachel.thompson@example.com', 'rachelpass', '1515 Birch Ln', 'Ohio'),
('Sam Wilson', 'sam.wilson@example.com', 'sampassword', '1616 Pine St', 'Texas'),
('Tina Moore', 'tina.moore@example.com', 'tinapassword', '1717 Oak St', 'California'),
('Ursula King', 'ursula.king@example.com', 'ursulapassword', '1818 Maple Blvd', 'New York'),
('Victor Garcia', 'victor.garcia@example.com', 'victorpass', '1919 Fir St', 'Florida'),
('Wendy Rodriguez', 'wendy.rodriguez@example.com', 'wendy123', '2020 Birch Ave', 'Nevada'),
('Xander Hall', 'xander.hall@example.com', 'xanderpw', '2121 Cedar Ct', 'Oregon'),
('Yvonne Perez', 'yvonne.perez@example.com', 'yvonnepass', '2222 Elm Blvd', 'Illinois'),
('Zachary Martinez', 'zachary.martinez@example.com', 'zachpw', '2323 Pine Rd', 'Michigan'),
('Angela Young', 'angela.young@example.com', 'angelapass', '2424 Maple St', 'Ohio'),
('Ben Turner', 'ben.turner@example.com', 'benpassword', '2525 Oak Dr', 'Texas'),
('Chloe Harris', 'chloe.harris@example.com', 'chloepw', '2626 Cedar Blvd', 'California'),
('Daniel Wright', 'daniel.wright@example.com', 'danielpw', '2727 Elm Ln', 'New York'),
('Evelyn Moore', 'evelyn.moore@example.com', 'evelyn123', '2828 Oakwood St', 'Florida'),
('Frank Foster', 'frank.foster@example.com', 'frankpass', '2929 Birch Blvd', 'Nevada'),
('Grace Campbell', 'grace.campbell@example.com', 'gracepw', '3030 Pine Rd', 'Oregon'),
('Helen Murphy', 'helen.murphy@example.com', 'helenpassword', '3131 Maple Ct', 'Illinois'),
('Ivy Nelson', 'ivy.nelson@example.com', 'ivynelsonpw', '3232 Fir Ln', 'Michigan'),
('John Cook', 'john.cook@example.com', 'johnpassword', '3333 Cedar Dr', 'Ohio'),
('Kathy Harris', 'kathy.harris@example.com', 'kathypassword', '3434 Pinecrest Ave', 'Texas'),
('Liam Green', 'liam.green@example.com', 'liam1234', '3535 Oak Ln', 'California'),
('Mason Perez', 'mason.perez@example.com', 'masonpass', '3636 Birch Rd', 'New York'),
('Nina Clark', 'nina.clark@example.com', 'ninapassword', '3737 Elm Way', 'Florida'),
('Oscar Lewis', 'oscar.lewis@example.com', 'oscarpassword', '3838 Maple Dr', 'Nevada'),
('Penny Martinez', 'penny.martinez@example.com', 'pennypass', '3939 Fir Ct', 'Oregon'),
('Quincy Mitchell', 'quincy.mitchell@example.com', 'quincy123', '4040 Pine Ln', 'Illinois'),
('Rita Roberts', 'rita.roberts@example.com', 'ritapassword', '4141 Cedar Rd', 'Michigan'),
('Steven Collins', 'steven.collins@example.com', 'steven123', '4242 Birch Ct', 'Ohio'),
('Tracy Hill', 'tracy.hill@example.com', 'tracypassword', '4343 Oak Rd', 'Texas'),
('Uma Grant', 'uma.grant@example.com', 'umapassword', '4444 Maple Blvd', 'California'),
('Vera Green', 'vera.green@example.com', 'veragreenpass', '4545 Pinehill Dr', 'New York'),
('William Scott', 'william.scott@example.com', 'william123', '4646 Elm St', 'Florida'),
('Xena Thomas', 'xena.thomas@example.com', 'xenapassword', '4747 Birch Ave', 'Nevada'),
('Yasmin Parker', 'yasmin.parker@example.com', 'yasminpass', '4848 Cedar Ln', 'Oregon'),
('Zane Ross', 'zane.ross@example.com', 'zanepassword', '4949 Oak Dr', 'Illinois');

USE users